### ISSUE TITLE
An error occurred while adding you to the Administrators group.

### ISSUE THREAD

**Issue by SkarkByte** [pseymour/MakeMeAdmin#104] opened 2023-10-12 17:57 UTC
Hi ,

I am getting the below error .. any ideas why and how to resolve? 

Thanks!!

An error occurred while adding you to the Administrators group.
Error Message: The server was unable to process the request due to an internal error. For more information about the error, either turn on IncludeExceptionDetaillnFaults (either from ServiceBehaviorAttribute or from the < serviceDebug> configuration behavior) on the server in order to send the exception information back to the client; or turn on tracing as per the Microsoft.NET Framework SDK documentation and inspect the server trace logs.

**Comment by pseymour** [comment] 2023-10-14 14:34
This is usually caused by a corrupt users.xml file. Search for it and delete it. It is in different places, depending on the version you have, so you have to search. It will be in a Make Me Admin folder though.

**Comment by SkarkByte** [comment] 2023-10-16 12:13
that worked thank you !!

**Closed** 2023-10-16 20:22 UTC
