### ISSUE TITLE
Cannot Install - Insufficient Privileges

### ISSUE THREAD

**Issue by Machine5464** [pseymour/MakeMeAdmin#15] opened 2020-05-26 19:28 UTC
I'm trying to install this using the 64-bit installer but its failing. I'm getting the error "Service 'Make Me Admin' (MakeMeAdmin) failed to start. Verify that you have sufficient privileges to start system service. I am running the installer on a local administrator account.

Any ideas?

**Comment by Machine5464** [comment] 2020-06-11 19:01
Main failure seems to be a 1920 error, failure to start the services. Running this as admin ofcourse, tried added the admin credentials directly to the service. The install folder and service are there when the install fails and are deleted once the install is cancelled.

Action start 15:12:15: INSTALL.
Action start 15:12:15: FindRelatedProducts.
Action ended 15:12:15: FindRelatedProducts. Return value 1.
Action start 15:12:15: LaunchConditions.
Action ended 15:12:15: LaunchConditions. Return value 1.
Action start 15:12:15: ValidateProductID.
Action ended 15:12:15: ValidateProductID. Return value 1.
Action start 15:12:15: CostInitialize.
Action ended 15:12:15: CostInitialize. Return value 1.
Action start 15:12:15: FileCost.
Action ended 15:12:15: FileCost. Return value 1.
Action start 15:12:15: CostFinalize.
Action ended 15:12:15: CostFinalize. Return value 1.
Action start 15:12:15: MigrateFeatureStates.
Action ended 15:12:15: MigrateFeatureStates. Return value 0.
Action start 15:12:15: InstallValidate.
Action ended 15:12:15: InstallValidate. Return value 1.
Action start 15:12:15: RemoveExistingProducts.
Action ended 15:12:15: RemoveExistingProducts. Return value 1.
Action start 15:12:15: InstallInitialize.
Action ended 15:12:15: InstallInitialize. Return value 1.
Action start 15:12:15: ProcessComponents.
Action ended 15:12:15: ProcessComponents. Return value 1.
Action start 15:12:15: UnpublishFeatures.
Action ended 15:12:15: UnpublishFeatures. Return value 1.
Action start 15:12:15: StopServices.
Action ended 15:12:15: StopServices. Return value 1.
Action start 15:12:15: DeleteServices.
Action ended 15:12:15: DeleteServices. Return value 1.
Action start 15:12:15: RemoveRegistryValues.
Action ended 15:12:15: RemoveRegistryValues. Return value 1.
Action start 15:12:15: RemoveShortcuts.
Action ended 15:12:15: RemoveShortcuts. Return value 1.
Action start 15:12:15: RemoveFiles.
Action ended 15:12:15: RemoveFiles. Return value 1.
Action start 15:12:15: RemoveFolders.
Action ended 15:12:15: RemoveFolders. Return value 1.
Action start 15:12:15: CreateFolders.
Action ended 15:12:15: CreateFolders. Return value 1.
Action start 15:12:15: InstallFiles.
Action ended 15:12:15: InstallFiles. Return value 1.
Action start 15:12:15: CreateShortcuts.
Action ended 15:12:15: CreateShortcuts. Return value 1.
Action start 15:12:15: WriteRegistryValues.
Action ended 15:12:15: WriteRegistryValues. Return value 1.
Action start 15:12:15: InstallServices.
Action ended 15:12:15: InstallServices. Return value 1.
Action start 15:12:15: SchedServiceConfig.
Action start 15:12:16: RollbackServiceConfig.
Action ended 15:12:16: RollbackServiceConfig. Return value 1.
Action start 15:12:16: ExecServiceConfig.
Action ended 15:12:16: ExecServiceConfig. Return value 1.
Action ended 15:12:16: SchedServiceConfig. Return value 1.
Action start 15:12:16: StartServices.
Action ended 15:12:16: StartServices. Return value 1.
Action start 15:12:16: RegisterUser.
Action ended 15:12:16: RegisterUser. Return value 1.
Action start 15:12:16: RegisterProduct.
Action ended 15:12:16: RegisterProduct. Return value 1.
Action start 15:12:16: PublishFeatures.
Action ended 15:12:16: PublishFeatures. Return value 1.
Action start 15:12:16: PublishProduct.
Action ended 15:12:16: PublishProduct. Return value 1.
Action start 15:12:16: InstallFinalize.
MSI (s) (90:20) [15:16:20:215]: Product: Make Me Admin -- Error 1920. Service 'Make Me Admin' (MakeMeAdmin) failed to start.  Verify that you have sufficient privileges to start system services.

**Comment by pseymour** [comment] 2020-06-19 01:29
Is the Server service disabled? Make Me Admin depends on that.

**Comment by Machine5464** [comment] 2020-06-19 01:37
The service fails to start.

When doing the install, it gets partially through. Directory is created in program files and the service is listed in services. But the error "Service 'Make Me Admin (MakeMeAdmin) failed to start. Verify that you have sufficient privilege's to start system services." This occurs when running the install as a local admin.

While the install is pending, the service is stopped. When I attempt to start it, it tries and then fails reporting the message "The Make Me Admin service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs." This occurs when running services as an administrator account.

**Comment by pseymour** [comment] 2020-06-19 01:57
But I asked about the Server service.

**Comment by Machine5464** [comment] 2020-06-19 02:25
Sorry, I misunderstood. Yep, Server service is running when the install fails. Security accounts manager, remote procedure call (RPC), DCOM server process launcher, and RPC endpoint mapper services are all running as well.

**Comment by Machine5464** [comment] 2020-07-09 19:46
Not sure what the cause was, but by deleting "HKLM\SOFTWARE\Policies\Sinclair Community College" Make Me Admin installs and the service runs now.

**Comment by pseymour** [comment] 2020-07-09 22:56
Odd. Do you happen to know if there was anything in the key before deleting it?

**Comment by Machine5464** [comment] 2020-07-10 20:36
User 1
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Sinclair Community College]

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Sinclair Community College\Make Me Admin]
"Allow Remote Requests"=dword:00000001
"Remove Admin Rights On Logout"=dword:00000001
"Admin Rights Timeout"=dword:00000014

User 2
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Sinclair Community College]

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Sinclair Community College\Make Me Admin]
"Allow Remote Requests"=dword:00000001
"Remove Admin Rights On Logout"=dword:00000001
"Admin Rights Timeout"=dword:00000014

**Comment by Machine5464** [comment] 2020-07-13 22:12
Had a chance to test this again, it seems specifically that subkey "Allow Remote Requests"=dword:00000001" causes the issue. If I delete that only while leaving the other subkey's in the post above it still installs. Hope that helps.

**Comment by pseymour** [comment] 2020-07-14 13:01
I was able to re-create this on a machine with the "Intel Graphics Command Center Service" running. It looks like it's using the same port as Make Me Admin's TCP connection. Do you have anything on the affected machines using TCP on port 808? You can use `netstat.exe -ab` to check.

In my case, I see

`TCP  0.0.0.0:808            hostname:0               LISTENING`
`[OneApp.IGCC.WinService.exe]`

As a workaround, I was able to disable the IGCC and install Make Me Admin, but we probably need a better solution. Changing the port that MMA uses, or allowing port sharing.

**Comment by Machine5464** [comment] 2020-07-20 21:19
It looks like OneApp.IGCC.WinServer.exe (Intel(R) Graphics Command Center Utility) is running on TCP 808 for us as well. If I end that service I can install MakeMeAdmin, no registry modifications required.

**Comment by Machine5464** [comment] 2020-07-29 23:29
Running the following command as an admin prior to the install allows it to succeed.

Stop-Process -name OneApp.IGCC.WinService -Force

**Comment by pseymour** [comment] 2020-08-10 12:52
I have created code to check for other processes using the same port, starting the port sharing service, etc. But as it turns out, the Intel graphics service in question is not setup to allow port sharing.  I have manually changed their service's configuration on my PC, and then my port sharing code works, but I doubt that is something everyone wants to do on all of their PCs. We will have to wait for Intel to update their driver to allow port sharing, in order to test that part of this new code.

[relevant post from the Intel support community](https://community.intel.com/t5/Graphics/Service-for-Intel-R-Graphics-Command-Center-igccservice-blocks/m-p/676372#M80139)

In the meantime, I have also added an option to change Make Me Admin's port. That can be tested independently of Intel's progress.

**Comment by pseymour** [comment] 2020-08-10 16:14
last commit for this issue: 420eaad6f5cd2e612012ee790f924c3d31908f1a

code branch:  https://github.com/pseymour/MakeMeAdmin/tree/issue-15

You can try the option to change the TCP port used by the service. The testing of the port sharing code will have to wait for Intel to fix their driver.

**Comment by pseymour** [comment] 2020-09-29 12:03
I'm happy to report that I received an Intel driver update today for one of my affected devices. I am unhappy to report that it did absolutely nothing to fix this issue.

I have created a [PowerShell script](https://gist.github.com/pseymour/2b0742b211f923bae1018ee49c67c448) to check the config files for the Intel Graphics Command Center Service. For the relevant files, you should get output similar to the following:

`<netTcpBinding>`
`    <binding name="IGCCNetTcpBinding" maxReceivedMessageSize="512000" sendTimeout="00:05:00">`
`        <security mode="Transport">`
`.`
`.`
`.`
`</netTcpBinding>`

That `<netTcpBinding>` tag should have an attribute on it that says `portSharingEnabled="true"`.  Mine does not, as of today. That means Intel is using the port and not allowing other applications to share the same port.

For my work and personal devices, I'm left with no option but to disable this service on all devices.

**Comment by Machine5464** [comment] 2020-10-16 15:46
I've been running this on PS on computers when the issue pops up as a quick fix. I haven't had time to look at just disabling the igccservice yet. From what I can find, the Intel Graphics Connand Center itself can be uninstalled and isn't necessary, but not sure if the intel drivers rely on the service otherwise.

Stop-Service igccservice
Start-Service MakeMeAdmin

**Comment by pseymour** [comment] 2020-10-16 16:23
Yep, that's perfectly valid. Really, the issue is whether the igccservice starts before Make Me Admin. If igccservice starts first, it blocks any other software from using port 808.

I have the service disabled on a little over 1,300 machines, without issue so far. I went this route, because we keep our drivers up-to-date with the Dell utilities. If I remove the Command Center, I figure it's just a matter of time before Intel releases an updated version and "helpfully" puts the service back.

**Comment by pseymour** [comment] 2020-12-08 01:38
Update:  Seems Intel may have fixed the driver back in October. I haven't tried it out yet.

[relevant post from the Intel support community](https://community.intel.com/t5/Graphics/Service-for-Intel-R-Graphics-Command-Center-igccservice-blocks/m-p/676372#M80139)

**Comment by Machine5464** [comment] 2021-01-11 19:35
Tested the driver for about a month on a few computers and haven't had this issue come back. It's not worth it to manually update the driver for us as disabling the service seems to work and is easy to apply.

**Comment by pseymour** [comment] 2021-02-01 16:12
I've done some testing with the Intel service in question, along with a simple little service I created myself to "hog" port 808. I'm pretty satisfied that Make Me Admin handles these conditions better now, and I've merged the branch for this issue into the main branch.

**Closed by pseymour** 2021-02-01 16:12 UTC
Labels: bug
