### ISSUE TITLE
Azuse domain group and user support

### ISSUE THREAD

**Issue by ikernel589** [pseymour/MakeMeAdmin#91] opened 2023-04-01 01:19 UTC
Does it support Azure AD domain joined windows machines?

I use graph to get the SID by the Azure Group Object ID.
https://developer.microsoft.com/en-us/graph/graph-explorer

If I am a domain admins, MMA recognizes "You already have administrator right"
If I am not domain admins but in the Allows Entities. MMA returns "you are not authorized to use this application"

**Comment by pseymour** [comment] 2023-04-18 18:50
Duplicate of #30

**Closed by pseymour** 2023-04-18 18:50 UTC
